# Usar Node.js LTS
FROM node:20

# Diretório de trabalho no container
WORKDIR /app

# Copiar package.json e package-lock.json
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar todo o código
COPY . .

# Expor porta do backend
EXPOSE 5000

# Comando para iniciar o backend
CMD ["npm", "start"]
